export const ROUTES = {
  PUBLIC_HOME: '/',
  CATEGORIES: '/categories',
  CATEGORY_PLACES: '/categories/:categorySlug',
  PLACE_DETAILS: '/places/:placeSlug',
  BOOK_SERVICE: '/places/:placeSlug/book/:serviceId',
  BOOKING_STATUS: '/booking/:bookingCode',
  DISPLAY: '/display/:placeSlug',

  OWNER_LOGIN: '/owner/login',
  OWNER_REGISTER: '/owner/register',
  OWNER_ONBOARDING: '/owner/onboarding',
  OWNER_DASHBOARD: '/owner/dashboard',
  OWNER_CREATE_PLACE: '/owner/place/create',
  OWNER_EDIT_PLACE: '/owner/place/edit',
  OWNER_SERVICES: '/owner/services',
  OWNER_QUEUE: '/owner/queue',
  OWNER_BOOKINGS: '/owner/bookings',
  OWNER_REPORTS: '/owner/reports',
  OWNER_SETTINGS: '/owner/settings',

  ADMIN_LOGIN: '/admin/login',
  ADMIN_DASHBOARD: '/admin/dashboard',
  ADMIN_PLACE_REQUESTS: '/admin/place-requests',
  ADMIN_PLACE_REQUEST_DETAILS: '/admin/place-requests/:id',
  ADMIN_PLACES: '/admin/places',
  ADMIN_CATEGORIES: '/admin/categories',
  ADMIN_USERS: '/admin/users',
  ADMIN_REPORTS: '/admin/reports',
};